### ISSUE TITLE
As a Toda@Eurac user I want that last bugs are fixed in order to use the web component on the Eurac's screens.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today#10]
Bugs to be solved:
- [x] #5
- [x] #6 
- [x] #7 
- [x] #8 
- [x] #9

**Comment by dulvui** [comment]
@sseppi ready for testing

**Comment by sseppi** [comment]
I share the link to the Web component:
- store: https://webcomponents.opendatahub.com/webcomponent/events-today?from=%2F
- full screen: https://webcomponents.opendatahub.com/webcomponent/events-today/fullscreen?attribs=PGV2ZW50cy10b2RheSBldmVudC1sb2NhdGlvbj0iRUMiIGV2ZW50LXJvdGF0aW9uLWludGVydmFsPSI2MCIgZm9udC1uYW1lPSJNaWxvIEJvbGQiIGZvbnQtdXJsPSJodHRwczovL3MzLmV1LXdlc3QtMS5hbWF6b25hd3MuY29tL2l0LmJ6Lm5vaS50b2RheS5ldXJhYy5nYWxsZXJ5L21pbG8tcHJvL3N0eWxlLmNzcyIgaW1hZ2UtZ2FsbGVyeS1pbnRlcnZhbD0iNjAiIGltYWdlLWdhbGxlcnktdXJsPSJodHRwczovL3MzLmV1LXdlc3QtMS5hbWF6b25hd3MuY29tL2l0LmJ6Lm5vaS50b2RheS5ldXJhYy5nYWxsZXJ5IiBsYW5ndWFnZS1yb3RhdGlvbi1pbnRlcnZhbD0iMTAiIG1heC1ldmVudHM9IjQiIHJvb209IiI%252BPC9ldmVudHMtdG9kYXk%252BCg%253D%253D
