### ISSUE TITLE
Wrong room name diplayed for an event.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today#11]
While testing the web component it emerged a problem in displaying correctly events that takes place into different rooms and days.

The problem emerged with the event at the following link:

https://v2-beta.databrowser.opendatahub.com/dataset/detail/tourism/v1/EventShort/eventshort-18880?source=eurac#event-details

As you can see, in the screenshot below, which is referring to the Conference Hall, the system is displaying the contents of the event happening in the "Seminar 1,2 and 3 unified".

![Screenshot from 2023-07-03 15-58-40](https://github.com/noi-techpark/webcomp-events-today/assets/7909989/0a40089d-8669-474c-a525-afb8880f6c61)

I suppose that the problem is related to events with more rooms and day associated that are taking the wrong "sub event".
The web component it should render the following information:

- evet date: 08,07/2023
- event start - end: 11:00 - 13:00
- Room: Conference Hall
- Title: Policy Summer School: Diversity Governance and Securitization in the EU and Beyond (Here I see that there is also a sub title, but for the moment the client didn't ask to show it... Maybe it could happen in future)

To help you in debugging the problem, in the attached zip, you find all files with the configurated component that I went to Eurac.

[Files-Prod.zip](https://github.com/noi-techpark/webcomp-events-today/files/11937663/Files-Prod.zip)

If you have more question, feel free to contact me.

**Comment by dulvui** [comment]
@sseppi The room filtering didn't work anymore, since we changed to `EventShort/GetbyRoomBooked`. For some reasons, the rawfilters don't work there. No I filter for the correct room in JS

**Comment by sseppi** [comment]
@sseppi will test it on monday and then provide the go to Simon.
