### ISSUE TITLE
Show also the "subtitle" under the title of an event.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today#14]
As a Eurac Event organizator I want to see also the sub title (if exists) of an event, to better guide the participants of events that are taking place in more rooms.

In case of long titles and/or subtitles, the component should behave as follows:

- if there isn't a subtitle, the title should be rendered on two lines and, in case there is not enough space, cut the text and add 3 dots at the end;
- if there is a subtitle, the title and the subtitle should be rendered on max one line each and, in case there is not enough space, cut the text and add 3 dots at the end;

Bleow I share the screenshot for the css configuration of the fonts:

**Overview monitor (more events are shown)**
![image](https://github.com/noi-techpark/webcomp-events-today/assets/7909989/28a70157-8668-4377-8d5e-44607e1bf9c6)

**Single room monitor (max one event per time is shown)**
![image](https://github.com/noi-techpark/webcomp-events-today/assets/7909989/30081715-acc3-4f11-9212-ce4ea2947cc6)

Here below I share the link to the font to be used for all non bold texts and the demo PDF of the two monitor types.

[Inter-3.15.zip](https://github.com/noi-techpark/webcomp-events-today/files/13175225/Inter-3.15.zip)
[Slide 16_9 - 1920x1080 - monitor reception - sottotitoli.pdf](https://github.com/noi-techpark/webcomp-events-today/files/13175226/Slide.16_9.-.1920x1080.-.monitor.reception.-.sottotitoli.pdf)
[Slide 16_9 - 1920x1080 - monitors rooms - sottotitoli.pdf](https://github.com/noi-techpark/webcomp-events-today/files/13175227/Slide.16_9.-.1920x1080.-.monitors.rooms.-.sottotitoli.pdf)

**Comment by sseppi** [comment]
@dulvui I had a look in testing and is seems everything fine to me. You can put it in production an let me know once done

**Comment by dulvui** [comment]
@sseppi I deployed to production now

**Comment by RudiThoeni** [comment]
Hi 
I changed now on Backend Side, the Subtitle field is there example:
`"Subtitle": "Workshop 6: Using Podcasts with Secondary Learners",
`

**Comment by dulvui** [comment]
@RudiThoeni Great thank you! I adjusted now the webcomponent in testing to uses the `Subtitle` field.
I just saw that on production API the field is there but always empty
https://tourism.api.opendatahub.com/v1/EventShort/GetbyRoomBooked?startdate=1700823811278&enddate=1700870400000&eventlocation=EC&datetimeformat=uxtimestamp&onlyactive=true&sortorder=ASC

Is it working only on testing?

**Comment by RudiThoeni** [comment]
its on production, example here it is filled, https://tourism.api.opendatahub.com/v1/EventShort/GetbyRoomBooked?startdate=2023-12-27&enddate=2023-12-28
The subtitle is not present in each data only where they set it.....
