### ISSUE TITLE
Today@Eurac :avoid shohwing events with comment x

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today#5]
the 9 May 2023 in Seminar Room 7 of Eurac it was organized the following event event with two locations (Seminar Room 7 and Virtual Space 1):

https://databrowser.opendatahub.testingmachine.eu/dataset/raw/tourism/v1/EventShort/eventshort-20652

On Today@Eurac the Virtual Spaces shouldn't be displayed and, as you can see from the image that Eruac shared with mem it wasn't so.

![image001](https://github.com/noi-techpark/webcomp-events-today/assets/7909989/c3af3bfb-cf18-4b55-8543-10bce5769be4)

We should implement the same logic as for the Event@NOI that excludes the Events and the location that has an "x" in the comment as see in the JSON blew.
``` 
"RoomBooked":[
{
"Space":"SR007",
"Comment":
"",
"EndDate":"2023-05-10T16:00:00",
"Subtitle":"",
"SpaceDesc":"Seminar 7",
"SpaceType":"EC",
"StartDate":"2023-05-08T09:00:00",
"EndDateUTC":1683727200000,
"SpaceAbbrev":"Seminar 7",
"StartDateUTC":1683529200000,
"SpaceDescRoomMapping":"Seminar 7"
},
{
"Space":"VS1",
"Comment":
"x",
"EndDate":"2023-05-10T16:00:00",
"Subtitle":"",
"SpaceDesc":"Virtual Space 1",
"SpaceType":"VI",
"StartDate":"2023-05-08T09:00:00",
"EndDateUTC":1683727200000,
"SpaceAbbrev":"Virtual Space 1",
"StartDateUTC":1683529200000,
"SpaceDescRoomMapping":"Virtual Space 1"
}
],
```

**Comment by dulvui** [comment]
The API call getRoomsBooked is used now and so the rooms with comment "x" are not returned by the API.
