### ISSUE TITLE
Wrong Case-Sensitive Forms

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today#8]
The client shared with me the following screenshot.
<img width="1888" alt="image004" src="https://github.com/noi-techpark/webcomp-events-today/assets/7909989/eff3a606-e146-4023-9876-65949eca4085">
As the client said, the font of the texts marked in yellow are wrongly configured. The configuration should be taken from the ``Case-sensitive Forms`` in Figma, see the following link:
https://www.figma.com/file/tOUwp1JDoCDd5uEEOztmfc/Eurac-Videowall-nov.22?type=design&node-id=102-148&t=fXIvuUcYHKL6nepZ-0
If you login you should see in the inspect section the right configuration to be used, as you cans see in the screenshot below.
<img width="243" alt="image002" src="https://github.com/noi-techpark/webcomp-events-today/assets/7909989/67748eb0-2854-4bcb-b575-a7ef4bbabc04">
<img width="226" alt="image003" src="https://github.com/noi-techpark/webcomp-events-today/assets/7909989/b005532e-c2b6-4f5f-9fcb-48bd92970760">

**Comment by dulvui** [comment]
The font with the correct font-feature-settings is now uploaded to the S3 bucket and so the numbers are shown in the correct format now.
