### ISSUE TITLE
Event label on one raw

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today#9]
The client asked us to keep the labels of each events only on one raw, even if they are long. As you can see in the screenshot below, if the label textes are long they are rendered on two raw (see label highlighted in viola)
<img width="1888" alt="image004" src="https://github.com/noi-techpark/webcomp-events-today/assets/7909989/4c199ca4-5cde-4923-a4d3-2adac38efa36">
I suggest that, in case of long labels, the text is cut and three dots are shown at the end of the text to notify the user that it has been cut.

**Comment by dulvui** [comment]
The company name and event name have now a fixed maximum width and if they exceed the width, the overflowing characters get replaced by "..."
